apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: # we don't specify namespace as otherwise this causes conflicts
namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    releaseName: kube-prometheus-stack
    version: 52.1.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    additionalValuesFiles:
      - values-grafana.yaml
      - values-prometheus.yaml
