prometheus:
  agentMode: true

  prometheusSpec:
    replicas: 2

    remoteWrite:
    - url: http://mimir-nginx.mimir:8080/api/v1/push

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
       matchLabels:
         app: prometheus

## https://github.com/grafana/helm-charts/issues/1320
#mimir:
#  structuredConfig:
#    limits:
#      max_global_series_per_user: 1000000
