prometheus:
  agentMode: true

  prometheusSpec:
    replicas: 2

    remoteWrite:
      - name: grafana-cloud
        url: https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push
        basicAuth:
          username:
            name: api-tokens-grafana-cloud
            key: USERNAME_WRITE_PROMETHEUS
          password:
            name: api-tokens-grafana-cloud
            key: API_TOKEN_WRITE_PROMETHEUS

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
       matchLabels:
         app: prometheus

# https://github.com/grafana/helm-charts/issues/1320
mimir:
  structuredConfig:
    limits:
      max_global_series_per_user: 1000000
