apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster

resources:
  - resources/cluster/cluster.yaml
  - resources/cluster/hetzner-cluster.yaml

  - resources/control-plane/machine-health-check.yaml
  - resources/control-plane/machine-template.yaml
  - resources/control-plane/talos-control-plane.yaml


  - resources/worker-pool/machine-deployment.yaml
  - resources/worker-pool/machine-health-check.yaml
  - resources/worker-pool/machine-template.yaml
  - resources/worker-pool/talos-config-template.yaml

patches:
  - path: patches/hcloud-hetznerCluster-placementGroup_patch.yaml
  - path: patches/hcloud-mt-control-plane-placementGroup_patch.yaml
  - path: patches/hcloud-mt-md-0-placementGroup_patch.yaml
