apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacppt-controller-manager
  namespace: cacppt-system
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
