apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    namespace: traefik
    version: 10.3.2
    valuesFile: values.yaml
