apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
  name: example-app
spec:
  ports:
    - name: 8080-80
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: example-app
  type: ClusterIP
