apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ../../../base/external-dns
  - https://github.com/kubernetes-sigs/external-dns//kustomize?master


# tutorial at https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
