apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/provider.yaml

patches:
  - target:
      kind: Deployment
      name: cacppt-controller-manager
    patch: |-
      spec:
        template:
          spec:
            tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
