apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - https://github.com/kubernetes-sigs/external-dns//kustomize?master
  - external-secret-cloudflare-api-token.yaml

patches:
  - path: patches/deployment-add-args.yaml
  - path: patches/deployment-add-env-vars.yaml

# tutorial at https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
