apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: cilium
    version: 1.14.1
    repo: https://helm.cilium.io/
    namespace: kube-system
