ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList:
    - 10.244.0.0/16 # same as flannel for convenience
kubernetesProxyReplacement: strict
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - DAC_OVERRIDE
    - FOWNER
    - IPC_LOCK
    - KILL
    - NET_ADMIN
    - NET_RAW
    - SETGID
    - SETUID
    - SYS_ADMIN
    - SYS_RESOURCE
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE



cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445

# rollOutCiliumPods: true
# priorityClassName: "system-node-critical"

# hubble:
#   metrics:
#     enabled:
#       - dns:query;ignoreAAAA
#       - drop
#       - tcp
#       - flow
#       - icmp
#       - http
#   relay:
#     enabled: true
#     rollOutPods: true
#   ui:
#     enabled: true
#     rollOutPods: true

# operator:
#   rollOutPods: true
#   priorityClassName: "system-node-critical"
