apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-password-hash
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    deletionPolicy: "Retain"
  data:
    - secretKey: ADMIN_PASSWORD_HASH
      remoteRef:
        conversionStrategy: Default
        key: /cloudlab/prod/loft/ADMIN_PASSWORD_HASH
        decodingStrategy: None
