apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - ../../../../base/addons/ingress-nginx

helmCharts:
  - name: ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: ingress-nginx
    version: 4.7.1
    repo: https://kubernetes.github.io/ingress-nginx
