apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: host-namespaces-exception
spec:
  exceptions:
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
        - autogen-host-namespaces
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Daemonset
          namespaces:
            - monitoring
          names:
            - kube-prometheus-stack-prometheus-node-exporter*
