apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: host-port-exception
spec:
  exceptions:
    - policyName: disallow-host-ports
      ruleNames:
        - autogen-host-ports-none
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Daemonset
          namespaces:
            - delta
          names:
            - important-tool*
