apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

#helmCharts:
#  - name: argo-cd
#    valuesFile: values.yaml
#    releaseName: argo-cd
#    version: 5.46.2
#    repo: https://argoproj.github.io/argo-helm
#    namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.2/manifests/ha/install.yaml
  - resources

patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
