apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: argo-cd
    valuesFile: values.yaml
    releaseName: argo-cd
    version: 5.46.2
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd

resources:
  - resources/in-cluster.yaml
  - resources/addons-project.yaml
  - resources/applicationset-addons.yaml

patches:
  - path: patches/argocd-cm.yaml
