apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mimir

helmCharts:
  - name: mimir-distributed
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: mimir
    version: 5.1.3
    repo: https://grafana.github.io/helm-charts
