apiVersion: apps/v1
kind: Deployment
metadata:
  name: caph-controller-manager
  namespace: caph-system
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
