apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

resources: [ resources ]

helmCharts:
  - name: crossplane
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: crossplane
    namespace: crossplane-system
    version: 1.14.0
    repo: https://charts.crossplane.io/stable # this is the stable release channel
