apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_VERSION}
      configPatches:
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
        - op: add
          path: /cluster/apiServer/admissionControl/0/configuration/exemptions/namespaces
          value:
            - kube-system
            - loki
  infrastructureTemplate:
    kind: HCloudMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: "${CLUSTER_NAME}-control-plane"
