apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

resources:
  - ../../../base/crossplane
  - provider-aws-iam.yaml

helmCharts:
  - name: crossplane
    includeCRDs: true
#    valuesFile: values.yaml
    releaseName: crossplane
    version: 1.12.2
    repo: https://charts.crossplane.io/stable # this is the stable release channel
