apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    deletionPolicy: "Retain"
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        conversionStrategy: Default
        key: /cloudlab/prod/cloudflare/all_zones/dns_edit/CF_API_TOKEN
        decodingStrategy: None
