apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster

helmCharts:
  - name: capi-hcloud-talos
    includeCRDs: false
    releaseName: cloudlab-cluster
    version: 0.5.0
    valuesFile: values.yaml
    repo: https://cyclingwithelephants.github.io/charts
    namespace: cluster

patches:
- path: enable-ipv4-worker-pool.yaml
- path: enable-ipv4-control-plane.yaml
- path: secret-is-automatically-namespaced.yaml
