apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # this allows us to use helmCharts in kustomization.yaml files
  # it's a convenient way to reference remote helm charts
  kustomize.buildOptions: --enable-helm
    
  # Crossplane requires us to change the default way ArgoCD uses to track resource ownership
  # https://docs.crossplane.io/knowledge-base/integrations/argo-cd-crossplane/#configuring-argo-cd-with-crossplane
  application.resourceTrackingMethod: annotation

  # it's generally considered best practice to disable the admin user
  admin.enabled: "true" # TODO: disable this once Authentik declarative config is working

  timeout.reconciliation: 3m0s
  timeout.hard.reconciliation: 5m0s

  url: https://argocd.prod.adamland.xyz

  dex.config: |
      connectors:
      - config:
          issuer: https://authentik.prod.adamland.xyz/application/o/argocd/
          clientID: VhCSqSGS9uTPxmTRDJymKwpl1TpQi6NYEPAebG2w
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
        name: authentik
        type: oidc
        id: authentik
