apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
#  namespace: argocd
data:
  # this is an alpha feature
  # https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Progressive-Syncs/
  #  applicationsetcontroller.enable.progressive.syncs: 'true'
#  redis.server: argo-cd-redis-ha-haproxy:6379
  server.insecure: "true"
