apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # this allows us to use helmCharts in kustomization.yaml files
  # it's a convenient way to reference remote helm charts
  kustomize.buildOptions: --enable-helm
  # Crossplane requires us to change the default way ArgoCD uses to track resource ownership
  # https://docs.crossplane.io/knowledge-base/integrations/argo-cd-crossplane/#configuring-argo-cd-with-crossplane
  application.resourceTrackingMethod: annotation
