apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      # role: iam-role
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-parameter-store
            key: aws_access_key_id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-parameter-store
            key: aws_secret_access_key
            namespace: external-secrets

  retrySettings:
    maxRetries: 3
    retryInterval: 20m
