apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      # role: iam-role
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-parameter-store
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-parameter-store
            key: secret-access-key
            namespace: external-secrets
