apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
  - ../../../base/external-secrets

helmCharts:
  - name: external-secrets
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: external-secrets
    version: 4.7.0
    repo: https://charts.external-secrets.io
