apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - resources/in-cluster.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.2/manifests/core-install.yaml  
  - resources/system-project.yaml
  - resources/applicationset-addons.yaml

patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
