apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia
spec:
  instances: 3
  # unsupervised: automated update of the primary once all replicas have been upgraded
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi