apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: namespaces
    releaseName: namespaces
    version: 0.2.0
    valuesFile: values.yaml
    repo: https://cyclingwithelephants.github.io/charts
