apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

helmCharts:
  - name: promtail
    includeCRDs: true
    releaseName: promtail
    version: 6.11.5
#    valuesFile: values.yaml
    repo: https://grafana.github.io/helm-charts
    namespace: logging
