apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
# https://grafana.com/orgs/cloudlabprod/hosted-logs/640440#sending-logs
- promtail.yaml # this is a temporary measure. Eventually I'll probably move to R2 with a full Loki setup

#helmCharts:
#  - name: loki
#    includeCRDs: true
#    releaseName: loki
#    version: 5.8.9
#    valuesFile: values.yaml
#    repo: https://grafana.github.io/helm-charts
#    namespace: logging
