apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.prod.adamland.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
