apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: velero
    includeCRDs: true
    releaseName: velero
    version: 5.1.3
    valuesFile: values.yaml
    repo: https://vmware-tanzu.github.io/helm-charts
    namespace: velero
