#--set-file credentials.secretContents.cloud=<FULL PATH TO FILE> \
#--set configuration.backupStorageLocation[0].name=<BACKUP STORAGE LOCATION NAME> \
#--set configuration.backupStorageLocation[0].provider=<PROVIDER NAME> \
#--set configuration.backupStorageLocation[0].bucket=<BUCKET NAME> \
#--set configuration.backupStorageLocation[0].config.region=<REGION> \
#--set configuration.volumeSnapshotLocation[0].name=<VOLUME SNAPSHOT LOCATION NAME> \
#--set configuration.volumeSnapshotLocation[0].provider=<PROVIDER NAME> \
#--set configuration.volumeSnapshotLocation[0].config.region=<REGION> \
#--set initContainers[0].name=velero-plugin-for-<PROVIDER NAME> \
#--set initContainers[0].image=velero/velero-plugin-for-<PROVIDER NAME>:<PROVIDER PLUGIN TAG> \
#--set initContainers[0].volumeMounts[0].mountPath=/target \
#--set initContainers[0].volumeMounts[0].name=plugins


credentials:
  secretContents:
    cloud:

configuration:
  backupStorageLocation:
  - name:
    provider:
    bucket:
    config:
      region:
  volumeSnapshotLocation:
  - name:
    provider:
    config:
      region:

initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:0.6.1
    volumeMounts:
      - mountPath: /target
        name: plugins
