apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
spec:
#  strategy:
#    type: RollingSync
#    rollingSync:
#      steps:
#        - matchExpressions:
#            - key: cloudlab/argocd-appset-progressive-sync-wave
#              operator: In
#              values:
#                - "-2"
#        - matchExpressions:
#            - key: cloudlab/argocd-appset-progressive-sync-wave
#              operator: In
#              values:
#                - "-1"
#        - matchExpressions:
#            - key: cloudlab/argocd-appset-progressive-sync-wave
#              operator: In
#              values:
#                - "0"
#        - matchExpressions:
#            - key: cloudlab/argocd-appset-progressive-sync-wave
#              operator: In
#              values:
#                - "1"
  generators:
  - matrix:
      generators:
        # enriches applications per directory in clusters/base with cluster labels
        - clusters: {}
        - git:
            repoURL: &repo https://github.com/cyclingwithelephants/cloudlab.git
            revision: HEAD
            directories:
              - path: manifests/prod/addons/*
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: system
      source:
        repoURL: *repo
        path: '{{.path}}'
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          # this option is needed for prometheus-operator because it has HUGE CRDs
          # TODO: find a way to apply this option only to prometheus-operator using this ApplicationSet
          - ServerSideApply=true
