apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://github.com/hetznercloud/csi-driver//deploy/kubernetes?main
  - https://github.com/hetznercloud/csi-driver//deploy/kubernetes/service-monitor?main # needs prometheus
  - https://raw.githubusercontent.com/hetznercloud/csi-driver/main/deploy/monitoring/grafana-dashboard.json
