apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://github.com/hetznercloud/csi-driver//deploy/kubernetes/?ref=v2.4.0
#  - https://github.com/hetznercloud/csi-driver//deploy/kubernetes/service-monitor/?ref=main # needs prometheus
#  - https://raw.githubusercontent.com/hetznercloud/csi-driver/main/deploy/monitoring/grafana-dashboard.json


# TODO: use client-side encryption with LUKS
# https://github.com/hetznercloud/csi-driver/blob/main/docs/kubernetes/README.md#volumes-encrypted-with-luks
