name: Kube diff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_DIR: pr
  TARGET_DIR: target
  ENVS_DIR: manifests/groups
  GOPATH: ${{ github.workspace }}/go

jobs:
  kube-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        path: ${{ env.PR_DIR }}

    - name: Checkout Target branch
      uses: actions/checkout@v3
      with:
        path: ${{ env.TARGET_DIR }}
        ref: ${{ github.event.pull_request.base.ref }}

    - name: setup kustomize
      shell: bash
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.1

    - run: go install github.com/cyclingwithelephants/cloudlab/hack/kubediff@git-diff

    - run: |
        kubediff
        ls -la
        pwd        

    - name: PR comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: output.txt
