name: Kube diff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_DIR: pr
  TARGET_DIR: target
  ENVS_DIR: manifests/groups
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read
  pull-requests: write

jobs:
  kube-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        path: ${{ env.PR_DIR }}

    - name: Checkout Target branch
      uses: actions/checkout@v3
      with:
        path: ${{ env.TARGET_DIR }}
        ref: ${{ github.event.pull_request.base.ref }}

    - name: setup kustomize
      shell: bash
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.1

    - run: go install github.com/cyclingwithelephants/cloudlab/hack/kubediff@git-diff

    - run: |
        kubediff
        ls -la
        pwd        

# PR comments
    - name: Install jq and curl
      run: sudo apt-get install -y jq curl

    - name: Comment on PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILES_PATTERN:
      run: |
        set -xeou pipefail
        PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
        PR_API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/comments"
        
        # Find all files that match the provided pattern
        ls output.txt-*
        FILES=$(ls output.txt-*)
        
        # Loop through each file and post its content as a comment
        for file in $FILES; do
            FILE_CONTENT=$(cat "$file")
            COMMENT_BODY="Content of file $file:\n\`\`\`\n$FILE_CONTENT\n\`\`\`"
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $PR_API_URL -d "{ \"body\": \"$COMMENT_BODY\" }"
        done
